install.packages("igraph")
install.packages("sna")
install.packages("network")
install.packages("intergraph")
library(intergraph)
library(sna)
library(igraph)
library(network)
g_ky <-read.graph("g_ky.graphml", format = "graphml")
g_ha <-read.graph("g_ha.graphml", format = "graphml")
g_do <-read.graph("g_do.graphml", format = "graphml")
g_ch <-read.graph("g_ch.graphml", format = "graphml")
g_ky1 <- asNetwork(g_ky)
g_ha1 <- asNetwork(g_ha)
g_do1 <- asNetwork(g_do)
g_ch1 <- asNetwork(g_ch)
gcor(g_ky1, g_ha1)
gcor(g_ky1, g_ch1)
gcor(g_ky1, g_do1)
gcor(g_ha1, g_ch1)
gcor(g_ha1, g_do1)
gcor(g_ch1, g_do1)
g_kh.Cor <- qaptest(list(g_ky1, g_ha1, g_do1, g_ch1), gcor, g1=1, g2=2, reps=1000)
g_kd.Cor <- qaptest(list(g_ky1, g_ha1, g_do1, g_ch1), gcor, g1=1, g2=3, reps=1000)
g_kc.Cor <- qaptest(list(g_ky1, g_ha1, g_do1, g_ch1), gcor, g1=1, g2=4, reps=1000)
g_hc.Cor <- qaptest(list(g_ky1, g_ha1, g_do1, g_ch1), gcor, g1=2, g2=4, reps=1000)
g_dc.Cor <- qaptest(list(g_ky1, g_ha1, g_do1, g_ch1), gcor, g1=3, g2=4, reps=1000)
summary(g_kh.Cor)
